kind: pipeline
type: kubernetes
name: website

steps:
- name: build_dev
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest
    registry: docker.magical.rocks
    cache_from: docker.magical.rocks/dev-website:latest
    repo: docker.magical.rocks/dev-website
    dockerfile: Dev.Dockerfile
- name: publish_frontend
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest
    cache_from: docker.magical.rocks/website:latest
    registry: docker.magical.rocks
    repo: docker.magical.rocks/website
    dockerfile: Dockerfile