kind: pipeline
type: kubernetes
name: website

steps:
- name: publish_frontend
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest
    cache_from:
      from_secret: docker_full_project_name
    registry:
      from_secret: docker_registry
    repo:
      from_secret: docker_repo
    dockerfile: Dockerfile